#site-setting
url : "https://shivang1209-dot.github.io"
github_repository: https://github.com/shivang1209-dot
theme: jekyll-theme-hacker
title: home/sh1v4ng
description: Welcome to my Portfolio/Write-up/Blogging Website since I'm not a Web Developer.
name: &name "Shivang"
show_downloads: false

#github page setting
github:
  is_project_page: false

#site-author
name : *name 
bio  : "Dev/Sec"

#footer
footer_left: 2025 SH1V4NG

#plugin
plugins:
  - jekyll-sitemap
  - jekyll-feed