title:            home/sh1v4ng
longtitle:        Shivang Tiwari 路 Cybersecurity
author:           Shivang Tiwari
email:            shivangtiwari2415@gmail.com
description: >
  Portfolio 路 Labs 路 Walkthroughs 路 Cybersecurity research notes by Shivang

version:          1.0
gitbook_version:  3.2.3

url:              "https://shivang1209-dot.github.io"
baseurl:          ""
rss:              RSS

theme:            jekyll-theme-hacker

github_repository: https://github.com/shivang1209-dot

toc:
  enabled: true
  enabled_index: true
  h_min: 1
  h_max: 3

favicon_path:     /assets/gitbook/images/favicon.ico

markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful
markdown_ext:             markdown,mkdown,mkdn,mkd,md

permalink:        /:categories/:year-:month-:day-:title:output_ext

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    sort_by: nav_order

ordered_collections:
  - pages
  - posts

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: post
      nav_order: 50
  - scope:
      path: ""
      type: posts
    values:
      layout: post

page_width:       860px

destination:      ./_site
incremental:      false
regenerate:       true

extra_css:
  - assets/gitbook/custom-local.css

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap