#site-setting
url: "https://shivang1209-dot.github.io"
baseurl: ""
github_repository: https://github.com/shivang1209-dot
theme: jekyll-theme-hacker
title: home/sh1v4ng
longtitle: Shivang Tiwari 路 Cybersecurity
description: Portfolio 路 Labs 路 Walkthroughs 路 Cybersecurity research notes by Shivang
show_downloads: false

#site-author
name: Shivang Tiwari
author: Shivang Tiwari
email: shivangtiwari2415@gmail.com
bio: "Delhi-based security researcher focused on offensive security, DFIR, and cloud attack simulations"

#github page setting
github:
  is_project_page: false

#footer
footer_left: 2024 Shivang Tiwari
footer_right: Privacy Policy

#plugin
plugins:
  - jekyll-sitemap
  - jekyll-feed

#markdown
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
